version: '3.7'

services:
  nginx:
    restart: always
    image: nginx:latest
    network_mode: host
    volumes:
      - ./localhost.crt:/localhost.crt
      - ./localhost.key:/localhost.key
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
