version: '3.7'

services:
  nginx:
    restart: always
    image: nginx:latest
    network_mode: host
    volumes:
      - ./log:/var/log/nginx
      - ./localhost.crt:/etc/nginx/localhost.crt
      - ./localhost.key:/etc/nginx/localhost.key
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # 反向代理
      # - ./config/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      # 本地目录
      - ./config/local-dir.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
